name: param_mitra
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.3.0
  google_generative_ai: ^0.4.6
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  flutter_markdown: ^0.7.6+2
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
